### ISSUE TITLE
[Hotkeys] Hotkey defaults are always set to the currently set hotkey after pressing "Reset to Defaults"

### ISSUE THREAD

**Issue by valkyrienyanko** [GodotModules/GodotModulesCSharp#93]
## Issue
Hotkey defaults are always set to the currently set hotkey after pressing "Reset to Defaults"

![image](https://user-images.githubusercontent.com/6277739/168504187-dca694c3-dc64-4277-a8c8-c981a9973047.png)
![image](https://user-images.githubusercontent.com/6277739/168504199-cbee9979-cc7b-4e99-9d1d-f034fb651b9e.png)
This should have been set to `A` but it was set to `BracketRight` (what it is currently set to)

Assuming `Reset to Defaults` was pressed at least once, the above will happen every time whether you press `Reset to Defaults` or the small reset button to the right of the hotkey.

Not that if `Reset to Defaults` is never pressed, the small reset button to the right of each hotkey works just fine. So why is it that `Reset to Defaults` button causes this issue?

## Steps to Reproduce
1. Launch game
2. Go to Options > Controls
3. Set any hotkey to something else
4. Press the small reset button to the right of the hotkey, keep doing it a few times, just notice it works fine
5. Press the "Reset to Defaults" button at the bottom
6. Notice hotkey defaults are always the currently selected hotkey now (in other words, whenever you reset the hotkey now its default is the currently set hotkey)
7. Try doing steps 3 to 4

## Relevant Code
https://github.com/GodotModules/GodotModulesCSharp/blob/5bf82e74781f2639cd749db5e640c21cf3bdb7fb/Scripts/UI/Options/UIOptionsControls.cs#L53-L61

https://github.com/GodotModules/GodotModulesCSharp/blob/5bf82e74781f2639cd749db5e640c21cf3bdb7fb/Scripts/UI/Options/UIHotkey.cs#L33-L39

https://github.com/GodotModules/GodotModulesCSharp/blob/5bf82e74781f2639cd749db5e640c21cf3bdb7fb/Scripts/Managers/HotkeyManager.cs#L45-L59

**Comment by irj** [comment]
Fixed in 42bc3bed38dcc25fe8c25cd9722d93539dffb1a7.
