### ISSUE TITLE
Allowing to set multiple hotkeys per action

### ISSUE THREAD

**Issue by valkyrienyanko** [GodotModules/GodotModulesCSharp#95]
> ⚠️ **IMPORTANT**: This issue is for the [dev branch](https://github.com/GodotModules/GodotModulesCSharp/tree/dev)

![image](https://user-images.githubusercontent.com/6277739/168715690-f2fd540d-7094-4b0f-854d-4be6ddb722a8.png)

Currently the code forces there to only use the first hotkey in each action. So for example for `player_move_left`, `A` would be set but the left arrow key `Left` would be discarded.

Notice the code only takes the first action.
https://github.com/GodotModules/GodotModulesCSharp/blob/cb10f338099cbb8c40ff741978eb694dba53b0fc/Scripts/Managers/HotkeyManager.cs#L72

Currently the hotkey map looks like this `Dictionary<Category, Dictioanry<Action, InputEventKey>>`. It will have to become `Dictionary<Category, Dictioanry<Action, List<InputEventKey>>>` Notice the introduction of the `List<T>` 

But perhaps because of #93 this is probably not the best idea. (To sum up #93, this happened because the data was not cloned properly on creating `new Dict(otherDict)`. Perhaps the data should be stored like this `Dictionary<Category, HotkeyData>` where `HotkeyData` would store everything.

There is another problem. How will the user be able to set multiple hotkeys through a UI like this?
![image](https://user-images.githubusercontent.com/6277739/168716538-492877c3-dbf9-4724-81f7-835601f72316.png)

When the user clicks on button to change hotkey; if the hotkey is different from the one that exists already it will add a additional hotkey to the list and will display it as a comma separated list in the button. This can't be the best way to display this information, I'm sure there is a much better way.

If this issue is solved that means the player can choose between arrow keys or WASD and I can add a new action called `ui_fullscreen` which toggles full screen with either `Alt + Enter` or `F11`. It's also good for people who use controllers.

**Comment by irj** [comment]
> Currently the hotkey map looks like this `Dictionary<Category, Dictioanry<Action, InputEventKey>>`. It will have to become `Dictionary<Category, Dictioanry<Action, List<InputEventKey>>>` Notice the introduction of the `List<T>`
> 
> But perhaps because of #93 this is probably not the best idea. (To sum up #93, this happened because the data was not cloned properly on creating `new Dict(otherDict)`. Perhaps the data should be stored like this `Dictionary<Category, HotkeyData>` where `HotkeyData` would store everything.

This issue would be solved by #103. Implementing the list would then easily be done by replacing the single `HotkeyInfo`/`InputEventInfo` with a list.

> When the user clicks on button to change hotkey; if the hotkey is different from the one that exists already it will add a additional hotkey to the list and will display it as a comma separated list in the button. This can't be the best way to display this information, I'm sure there is a much better way.

Most games that allow for additional hotkeys only allow for a finite, preset number of hotkeys for an action. This could be achieved by having multiple hotkey buttons side by side in the UI that correspond to the same action.

In this case, it would be easier to save the data as a nullable list with the length of the maximum possible hotkeys, so each additional hotkey can map 1-to-1 with the stored list.
